### ISSUE TITLE
v3.1.0 moved types to fastify-url-data-deprecated but doesn't re-export them and breaks existing installs

### ISSUE THREAD

**Issue by cmawhorter** [fastify/fastify-url-data#103]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

3.1.0

### Node.js version

12.22.7

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

I updated url-data to 3.1.0 and had some typescript errors and noticed it doesn't include types.  it looks like they were moved to fastify-url-data-deprecated, but not re-exported.

the solution seems to be to update to `@fastify/...` which -- from reading through the fastify issue on module plans -- seems like it should be a non-breaking major?  is bumping to v4 the recommended approach?

### Steps to Reproduce

npm i fastify-url-data@3.1.0

**Comment by mcollina** [comment]
cc @fastify/typescript 

I think your best bet is to update to the new module name.

**Comment by jsumners** [comment]
Use the new module name. There will not be any new v3 releases.
