### ISSUE TITLE
X-Forwarded-Host is not used even when trustProxy is set on fastify server

### ISSUE THREAD

**Issue by SeanReece** [fastify/fastify-url-data#124]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x.x

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Any

### Description

`@fastify/url-data` does not use `X-Forwarded-Host` header when composing request URL and instead only uses `Host` header. This could cause issues for applications behind a reverse proxy, for example, NGINX by default will rewrite `Host` header to the host set in the proxy_pass directive.

Fastify will set `req.hostname` to the value of `X-Forwarded-Host` header [when `trustProxy` option is set to true](https://www.fastify.io/docs/latest/Reference/Server/#factory-trust-proxy), and falls back to `Host` header otherwise.

I would be more than happy to submit a PR.

### Possible solution

In the source for fastify-url-data the host is retrieved using 
```js
const host = this.headers[':authority'] || this.headers.host
```

I believe we can instead use 
```js
const host = this.hostname
```
This would keep the implementation of hostname consistent with fastify

The implementation in fastify for hostname is as follows [link](https://github.com/fastify/fastify/blob/f1bd80e007b019a2708c5fc1ff8340b0082908e7/lib/request.js#L118)
```js
if (this.ip !== undefined && this.headers['x-forwarded-host']) {
  return getLastEntryInMultiHeaderValue(this.headers['x-forwarded-host'])
}
return this.headers.host || this.headers[':authority']
```

### Steps to Reproduce

```js
const fastify = require('fastify')

const app = fastify({ trustProxy: true })

app.register(require('@fastify/url-data'))

app.get('/', async (req) => {
  const urlData = req.urlData()

  console.log('headers: ', req.headers)
  console.log('url-data host:', urlData.host)
  console.log('fastify hostname: ', req.hostname)
})

app.inject({
  url: '/',
  headers: {
    Host: 'internal.example.com',
    'X-Forwarded-Host': 'example.com',
  },
})
```

Output:
```sh
headers:  {
  host: 'internal.example.com',
  'x-forwarded-host': 'example.com',
  'user-agent': 'lightMyRequest'
}
url-data host: internal.example.com
fastify hostname:  example.com
```

### Expected Behavior

Behaviour for setting hostname should be consistent with fastify server.

**Comment by Uzlopak** [comment]
Dont we have our own @fastify/forwarded library?

**Comment by SeanReece** [comment]
@Uzlopak Looks like @fastify/forwarded only handles the `X-Forwarded-For` header.
