### ISSUE TITLE
TypeScript-support: error TS2339: Property 'urlData' does not exist on type 'FastifyRequest<

### ISSUE THREAD

**Issue by honigkuchenbaer** [fastify/fastify-url-data#130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Writing code with types like

```
        handler:  async (req: FastifyRequest, reply: FastifyReply) => {
            const urlData = req.urlData()
```

won't compile with TypeScript because of the following error:

>  error TS2339: Property 'urlData' does not exist on type 'FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>

When I remove the type `FastifyRequest`, it works:

```
handler:  async (req, reply: FastifyReply) => {
    console.log(req.urlData)
```

I have seen in the source-code and the issues (https://github.com/fastify/fastify-url-data/issues/2#issuecomment-341320628), that this plugin is enhancing the `FastifyRequest`-interface with the `urlData`-property.
However, I can not make it to work somehow.

What is the correct approach, to use TypeScript and make `urlData` available in `FastifyRequest` interface?

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by Uzlopak** [comment]
I guess, because you would actually need to import the fastify-url-data package into your separate file, where you use FastifyRequest, so that typescript can hoist the additional typings.

**Comment by Eomm** [comment]
Is this solved?

**Comment by Uzlopak** [comment]
I think there is nothing to solve.

**Comment by multiwebinc** [comment]
@Eomm This worked for me, an `/app.ts`:

```js
import fastify from 'fastify';
import fastifyUrlData from '@fastify/url-data';

const server = fastify({
  // ... options
});

server.register(fastifyUrlData);
```
