### ISSUE TITLE
use `new URL` instead of `fast-uri`

### ISSUE THREAD

**Issue by gurgunday** [fastify/fastify-url-data#141]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

For the purposes of this plugin, using the built-in `new URL` seems to be a better choice as it is now [faster](https://github.com/fastify/fast-uri/issues/76) than `fast-uri` for parsing URLs

**Comment by Uzlopak** [comment]
We should investigate if all the cases are optimized and not only the instantiation. 

E.g. I optimized the performance of the MIMEType instanciation in nodejs, but getting variables of the MIMEType instance is still needing some additional work, and thus being slower than our implementation.

**Comment by Fdawgs** [comment]
@Uzlopak @gurgunday Given the discussion in #144 I think this can be closed? From looking at the benchmarks in that PR there's no real gains.

**Comment by Uzlopak** [comment]
I agree.
