### ISSUE TITLE
Http2 Support

### ISSUE THREAD

**Issue by briancw** [fastify/fastify-url-data#7]
Are there any plans to support Http2?

Currently, request.urlData() looks like the following when using http2

`{ scheme: undefined,
  userinfo: undefined,
  host: 'undefined',
  port: undefined,
  path: '/',
  query: 'foo=bar',
  fragment: undefined,
  reference: 'relative' }`

**Comment by jsumners** [comment]
PRs are welcome. I am not familiar with HTTP/2.

**Comment by Eomm** [comment]
Released in v2.4.0
