### ISSUE TITLE
multiple register

### ISSUE THREAD

**Issue by Eomm** [fastify/fastify-url-data#88]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

We should check with `fastify.hasDecorator()` before adding the decorator.

so the user may register the plugin multiple times without issue.

Idea from: https://github.com/fastify/fastify-http-proxy/pull/205

**Comment by sztobar** [comment]
Wow, mind If I try myself? It looks like something I should be able to implement with care 😁

**Comment by Eomm** [comment]
Yeah!
Go for it!

**Comment by jsumners** [comment]
@Eomm can you clarify how this issue occurs? I think it would be an error to register the plugin twice.

**Comment by Eomm** [comment]
I remember some plugins have this kind of logic since the utility is self-contained: it does not require any additional configuration nor context.

The occurs is that if we use this plugin to get the fancy utility across fastify's plugins, we could hit the error

**Comment by jsumners** [comment]
I still don't understand. Plugins that depend upon the functionality of this one should declare that through the `fastify-plugin` dependencies.
